version: '3.8'

services:
    mariadb:
        image: mariadb:latest
        environment:
            MARIADB_ROOT_PASSWORD: secret
            MARIADB_DATABASE: url_shortener
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - ./data:/var/lib/shortener
